site_name: Pagatu DIST - Desarrollo de Aplicaciones Distribuidas
site_url: https://262dist.github.io/pagatu/
docs_dir: docs

nav:
  - Inicio: index.md
  - Sílabos:
      - Sílabo DIST 2026-1: silabo_dist_2026_1.md
      - Sílabo DIST 2026-2: silabo_dist_2026_2.md
  - Propuesta de proyecto:
      - Contenido: propuesta-proyecto/contenido.md
      - Estructura estándar: propuesta-proyecto/OFICIAL_ESTRUCTURA_ESTANDAR.md
      - Propuesta de migración: propuesta-proyecto/propuesta_migracion.md
      - README: propuesta-proyecto/README.md
      - Acerca del proyecto: propuesta-proyecto/README_01_ACERCA_DEL_PROYECTO.md
      - Arquitectura detallada: propuesta-proyecto/README_02_ARQUITECTURA_DETALLADA.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.copy

plugins:
  - search
