name: lambda26-ec-eventos-py

services:
  ec-eventos-py:
    build: .
    container_name: lambda26-ec-eventos-py
    volumes:
      - ./app:/app
    working_dir: /app
    command: sleep infinity
    networks:
      - lambda26-kafka-net

networks:
  lambda26-kafka-net:
    external: true
    name: lambda26-kafka-net
