server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://pagatu-auth-ms:8080/.well-known/jwks.json
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: pagatu-catalogo-categorias
              uri: lb://pagatu-catalogo-ms
              predicates:
                - Path=/api/v1/categorias/**
            - id: pagatu-catalogo-productos
              uri: lb://pagatu-catalogo-ms
              predicates:
                - Path=/api/v1/productos/**
            - id: pagatu-orden-ordenes
              uri: lb://pagatu-orden-ms
              predicates:
                - Path=/api/v1/ordenes/**

            - id: pagatu-auth-login
              uri: lb://pagatu-auth-ms
              predicates:
                - Path=/api/v1/auth/**

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://pagatu-eureka:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never