server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: pagatu-catalogo-categorias
              uri: lb://pagatu-catalogo-ms
              predicates:
                - Path=/api/v1/categorias/**
            - id: pagatu-catalogo-productos
              uri: lb://pagatu-catalogo-ms
              predicates:
                - Path=/api/v1/productos/**

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://pagatu-eureka:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never