name: pagatu-pago-dev

services:
  postgres-pago-dev:
    image: postgres:16-alpine
    container_name: pagatu-postgres-pago-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: pagatu_pago_db
      POSTGRES_USER: pagatu
      POSTGRES_PASSWORD: pagatu
    ports:
      - "15435:5432"
    volumes:
      - pagatu_pago_dev_data:/var/lib/postgresql/data

volumes:
  pagatu_pago_dev_data:
