name: pagatu-cliente-dev

services:
  postgres-cliente-dev:
    image: postgres:16-alpine
    container_name: pagatu-postgres-cliente-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: pagatu_cliente_db
      POSTGRES_USER: pagatu
      POSTGRES_PASSWORD: pagatu
    ports:
      - "15433:5432"
    volumes:
      - pagatu_cliente_dev_data:/var/lib/postgresql/data

volumes:
  pagatu_cliente_dev_data:
