name: pagatu-cliente-prod

services:
  postgres-cliente:
    image: postgres:16-alpine
    container_name: pagatu-postgres-cliente
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    volumes:
      - pagatu_cliente_data:/var/lib/postgresql/data
    ports:
      - "25433:5432"
    networks:
      - pagatu-cliente-int

  pagatu-cliente-ms:
    build: .
    restart: unless-stopped
    depends_on:
      postgres-cliente:
        condition: service_healthy
    #ports:
    #  - "28084:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_HOST: pagatu-postgres-cliente
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    volumes:
      - ./logs:/app/logs
    networks:
      - pagatu-cliente-int

volumes:
  pagatu_cliente_data:

networks:
  pagatu-cliente-int:
    name: pagatu-cliente-int
