CREATE TABLE IF NOT EXISTS clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tipo_persona VARCHAR(10) NOT NULL,
    dni VARCHAR(8),
    ruc VARCHAR(11),
    nombre_completo VARCHAR(150),
    razon_social VARCHAR(150),
    direccion VARCHAR(255),
    email VARCHAR(150),
    whatsapp VARCHAR(20),
    PRIMARY KEY (id),
    UNIQUE (dni),
    UNIQUE (ruc)
);
