name: pagatu-auth-dev

services:
  postgres-auth-dev:
    image: postgres:16-alpine
    container_name: pagatu-postgres-auth-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: pagatu_auth_db
      POSTGRES_USER: pagatu
      POSTGRES_PASSWORD: pagatu
    ports:
      - "15431:5432"
    volumes:
      - pagatu_auth_dev_data:/var/lib/postgresql/data

volumes:
  pagatu_auth_dev_data: